### PR TITLE
I made some cool changes to your stupid bash script.

### PR DESCRIPTION
**Pull request by Crystallek**
Please don't look into the code, there are some very questionable variables. UWU

### CODE REVIEW

**Comment by furretpaws** [comment]
REALLY COOL PR GOOD JOB CRYSTALLEK
PLEASE BRYN ACCEPT IT UWU

**Comment by Crystallek** [comment]
HELLO BRYN TRAINOR, WHY CLOSED?!

**Comment by furretpaws** [comment]
:(

**Comment by ghost** [comment]
TRAINOR
ACCEPT NOW YOU STUPID AUSTRALIAN

I HOPE YOU GET KILLED BY A SPIDER

**Pull request closed without merging**
